MARKER_SIZE = 6
FPS = 5
CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080
CAMERA_VERTICAL_OFFSET = 0
CAMERA_HORIZONTAL_OFFSET = 0
FRAME_SIZE = (700, 500)

AUTO_BRIGHTNESS = 'Active'  # can be active or off
BALANCE_WHITE = 'OnDemand'
